swagger: '2.0'
info:
  title: Cutter API
  description: Dokument-Schnitt-Service
  version: "1.1.0"
schemes:
  - https
basePath: /v1
produces:
  - application/pdf
paths:
  /composedPdf:
    post:
      summary: Zusammenschnitt von Eingangsdokumenten
      description: Generiert aus mehreren Eingangs-Dokumenten ein Zieldokument.
      operationId: generateComposedPdf
      parameters:
        - name: dokumentInput
          in: body
          description: Input für ein einzelnes zu erzeugendes Dokument.
          required: true
          schema:
            $ref: '#/definitions/DokumentInput'
      tags:
        - Dokument
      responses:
        200:
          description: Ein zusammengefügtes Dokument
          schema:
            type: file
        default:
          description: Unerwarteter Fehler
          schema:
            $ref: '#/definitions/Error'
definitions:
  DokumentInput:
    type: object
    properties:
      zielDateiName:
        type: string
        description: |
          Empfohlener Datei-Name.
      dokumentenTeile:
        type: array
        description: |
          Sortierte Verweise auf Original-Dokumente, die zu einem Ziel-Dokument zusammenzufassen sind.
        items:
          $ref: '#/definitions/DokumentenTeil'
  DokumentenTeil:
    type: object
    properties:
      uri:
        type: string
        format: uri
        description: |
          Download-URI für das Original-Dokument.
      seitenNummern:
        type: array
        description: |
          Sortierte Seiten im Original-Dokument, die zu verwenden sind, 1-basiert.
        items:
          type: integer
          format: int32
  Error:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
          format: int32
        statusMessage:
          type: string
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
      title: Error
